name: release-build

on:
  push:
    tags:
      - 'v*'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get the version to publish
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login in GHCR
        uses: docker/login-action@v1
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create semantic_release_version.txt file
        run: touch semantic_release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Get the version
        id: get_version
        run: |
          echo VERSION=$(cat semantic_release_version.txt) >> $GITHUB_ENV
      - name: Build and push Docker image 
        if: ${{ env.VERSION != '' }}
        run: make publish
        env:
          VERSION: ${{ env.VERSION }}

       - name: Build to DockerHub
        run: docker build -t  oscarmontes/liberando-productos-oscarmontes:latest .

      - name: Push to DockerHub
        run: docker push oscarmontes/liberando-productos-oscarmontes:latest

    outputs:
      version: ${{ env.VERSION }}
