name: release-build

on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ main ]
    types: 
      - completed
  push:
    tags:
      - 'v*'
    
permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read


jobs:
  semantic-release:
    if: "${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.commits[0].message, 'chore(release):') }}"
    name: Semantic Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      
      - name: Setup package.json
        run: echo '{echo '{
             "name":"liberando-productos"
             ,"repository":{
             "type":"git", "url":"git@github.com:roberto-asir/practica-liberando-producto.git"
              },
             "dependencies":{
             "@semantic-release/exec":"6.0.2","@semantic-release/git":"10.0.1",
              "@semantic-release/github":"8.0.2",
              "@semantic-release/release-notes-generator":"10.0.3",
              "@semantic-release/changelog":"6.0.1",
              "semantic-release":"^19.0.2"
               },
               "release":{
                   "branches":[
                     "main"
         ],
         "plugins":[
          "@semantic-release/commit-analyzer",
           "@semantic-release/github",
            "@semantic-release/release-notes-generator",
           [
           "@semantic-release/changelog",
          {
          "changelogFile":"docs/CHANGELOG.md"
           }
         ],
         [
         "@semantic-release/exec",
          {
          "prepareCmd":"echo ${nextRelease.version} > semantic_release_version.txt"
          }
         ],
         [
         "@semantic-release/git",
         {
          "message":"chore(release):${nextRelease.version} \n\n${nextRelease.notes}"
          }
         ]
         ]
          },
          "version":"0.0.1",
          "devDependencies":{
         "minimist":"^1.2.5"
          }
         }' > package.json
         
      - name: Install dependencies
        run:  npm install
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login in GHCR
        uses: docker/login-action@v1
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        id: configure-login-dockerhub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create empty semantic_release_version.txt file
        run: touch semantic_release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Get the version
        id: get_version
        run: |
          echo VERSION=$(cat semantic_release_version.txt) >> $GITHUB_ENV


      - name: Build and push Docker image
        run: make publish
        env:
          VERSION: ${{ env.VERSION }}
